sudo: true

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y gettext

language: node_js

node_js:
  - "4.2.1"

cache:
  directories:
    - node_modules

script: npm run build

deploy:
  provider: script
  skip_cleanup: true
  script: ./deploy.sh
  on:
    branch: master
